In [1]:
import numpy as np

In [2]:
arr=np.array([1,2,3])  
arr  

array([1, 2, 3])

In [3]:
arr=np.array([1,2.,3.],ndmin=2)  
arr  

array([[1., 2., 3.]])

In [4]:
arr=np.array([12,45.,3.],dtype=complex)  
arr  

array([12.+0.j, 45.+0.j,  3.+0.j])

In [5]:
arr=np.array(np.mat('1 2;3 4'))  
arr

array([[1, 2],
       [3, 4]])

In [6]:
arr=np.array(np.mat('1 2;3 4'),subok=True)  
arr  

matrix([[1, 2],
        [3, 4]])

In [7]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y))  
z  

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [8]:
x=np.array([[1,2],[3,4]])  
y=np.array([[12,30]])  
z=np.concatenate((x,y), axis=0)  
z  

array([[ 1,  2],
       [ 3,  4],
       [12, 30]])

In [9]:
x=np.ma.arange(3)  
y=np.arange(3,6)  
x[1]=np.ma.masked  
x  
y 

array([3, 4, 5])

In [10]:
z1=np.concatenate([x,y])  
z2=np.ma.concatenate([x,y])  
z1  
z2

masked_array(data=[0, --, 2, 3, 4, 5],
             mask=[False,  True, False, False, False, False],
       fill_value=999999)

In [11]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b)  
c  

array([10, 20, 30, 40, 50, 60, 70, 80, 90, 11, 21, 31, 42, 52, 62, 73, 83,
       93])

In [12]:
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])  
b=np.array([[11, 21, 31], [42, 52, 62], [73, 83, 93]])  
c=np.append(a,b,axis=0)  
c  

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [11, 21, 31],
       [42, 52, 62],
       [73, 83, 93]])

In [13]:
x=np.arange(12)  
y=np.reshape(x, (4,3))  
x  
y  

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
x=np.arange(12)  
y=np.reshape(np.ravel(x),(3,4))  
x  
y  

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
x=np.arange(12)  
y=np.reshape(x, (4, 3), order='F')  
x  
y

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [16]:
a=np.array([0.4,0.5])  
b=np.sum(a)  
b  

0.9

In [17]:
a=np.array([0.4,0.5,0.9,6.1])  
x=np.sum(a, dtype=np.int32)  
x  

6

In [18]:
b=np.sum([15], initial=8)  
b  

23

In [19]:
a=np.random.randn(2,2)  
a  

array([[ 0.20987056,  0.20366475],
       [ 0.42794654, -0.99310963]])

In [20]:
a=np.random.randint(3, size=10)  
a  

array([2, 0, 1, 0, 2, 0, 0, 1, 1, 1])

In [21]:
a=np.random.random_integers(3)  
a  
b=type(np.random.random_integers(3))  
b  
c=np.random.random_integers(5, size=(3,2))  
c  

c:\users\dell\appdata\local\programs\python\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  """Entry point for launching an IPython kernel.
c:\users\dell\appdata\local\programs\python\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  This is separate from the ipykernel package so we can avoid doing imports until
c:\users\dell\appdata\local\programs\python\lib\site-packages\ipykernel_launcher.py:5: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  """


array([[4, 1],
       [5, 5],
       [1, 2]])

In [22]:
a=np.random.random_sample()  
a  
b=type(np.random.random_sample())  
b  
c=np.random.random_sample((5,))  
c  

array([0.36378907, 0.10568184, 0.56531199, 0.35884052, 0.69339746])

In [23]:
a=np.random.random()  
a  
b=type(np.random.random())  
b  
c=np.random.random((5,))  
c  

array([0.12730231, 0.68231771, 0.58910628, 0.67843509, 0.54824554])

In [24]:
a=np.random.ranf()  
a  
b=type(np.random.ranf())  
b  
c=np.random.ranf((5,))  
c  

array([0.76957978, 0.19502363, 0.73054382, 0.62751166, 0.54785436])

In [25]:
a=np.random.sample()  
a  
b=type(np.random.sample())  
b  
c=np.random.sample((5,))  
c  

array([0.01560403, 0.69174077, 0.19889411, 0.9793999 , 0.19209703])

In [26]:
a=np.random.choice(5,3)  
a  
b=np.random.choice(5,3, p=[0.2, 0.1, 0.4, 0.2, 0.1])  
b

array([1, 4, 2])

In [27]:
a=np.random.bytes(7)  
a  

b'0~$mV\x86Q'

In [28]:
a=np.arange(12)  
a  
np.random.shuffle(a)  
a  

array([ 5,  6,  2, 11,  7,  0,  1,  4,  8,  9,  3, 10])

In [29]:
a=np.random.permutation(12)  
a  

array([ 6,  1,  3,  4,  5,  0, 11,  2,  7,  9,  8, 10])

In [30]:
n, p = 10, .6  
s1= np.random.binomial(n, p, 10)  
s1  

array([3, 7, 9, 8, 9, 4, 4, 6, 4, 6])

In [31]:
np.random.chisquare(2,4)  
sum(np.random.binomial(9, 0.1, 20000) == 0)/20000.  

0.38585

In [32]:
dfno= 1.  
dfden = 48.  
s1 = np.random.f(dfno, dfden, 10)  
np.sort(s1)  

array([1.03436792e-03, 2.20547099e-02, 3.23757864e-02, 3.32440636e-02,
       4.47608863e-02, 2.45818364e-01, 4.73205441e-01, 1.09314493e+00,
       1.49561893e+00, 4.08661320e+00])

In [33]:
a=np.zeros(6)  
a  

array([0., 0., 0., 0., 0., 0.])

In [34]:
a=np.zeros((6,), dtype=int)  
a   

array([0, 0, 0, 0, 0, 0])

In [35]:
a=np.zeros((6,2))  
a  

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
s1=(3,2)  
a=np.zeros(s1)  
a  

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [37]:
a=np.zeros((3,), dtype=[('x', 'i4'), ('y', 'i4')])  
a  

array([(0, 0), (0, 0), (0, 0)], dtype=[('x', '<i4'), ('y', '<i4')])

In [38]:
a=np.array([2, 4, 6, 3**8])  
a  
b=np.log(a)  
b  
c=np.log2(a)  
c  
d=np.log10(a)  
d  

array([0.30103   , 0.60205999, 0.77815125, 3.81697004])

In [39]:
x=np.log([2, np.e, np.e**3, 0])  
x  


c:\users\dell\appdata\local\programs\python\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([0.69314718, 1.        , 3.        ,       -inf])

In [40]:
a=np.arange(12)  
b=np.where(a<6,a,5*a)  
b  

array([ 0,  1,  2,  3,  4,  5, 30, 35, 40, 45, 50, 55])

In [41]:
a=np.arange(12)  
b=np.where([[True, False], [True, True]],[[1, 2], [3, 4]],[[9, 8], [7, 6]])  
b  

array([[1, 8],
       [3, 4]])

In [42]:
x, y = np.ogrid[:3, :4]  
a=np.where(x > y, x, 10 + y)  
a  

array([[10, 11, 12, 13],
       [ 1, 11, 12, 13],
       [ 2,  2, 12, 13]])

In [43]:
x=np.array([[0,1,2],[0,2,5],[0,4,8]])  
y=np.where(x<4,x,-2)  
y  

array([[ 0,  1,  2],
       [ 0,  2, -2],
       [ 0, -2, -2]])

In [44]:
a=np.array([456,11,63])  
a  
b=np.argsort(a)  
b  

array([1, 2, 0], dtype=int64)

In [45]:
a = np.array([[0, 5], [3, 2]])  
indices = np.argsort(a, axis=0)  
indices  
np.take_along_axis(a, indices, axis=0)  

array([[0, 2],
       [3, 5]])

In [46]:
a = np.array([[0, 5], [3, 2]])  
indices = np.argsort(a, axis=1)    
indices  

array([[0, 1],
       [1, 0]], dtype=int64)

In [47]:
a = np.array([[0, 5], [3, 2]])  
indices = np.argsort(a, axis=1)  
indices  
np.take_along_axis(a, indices, axis=1)  

array([[0, 5],
       [2, 3]])

In [48]:
a= np.array([(0, 5), (3, 2)], dtype=[('x', '<i4'), ('y', '<i4')])  
a  
b=np.argsort(a, order=('x','y'))  
b  
c=np.argsort(a, order=('y','x'))  
c  

array([1, 0], dtype=int64)

In [49]:
a= np.arange(6).reshape((2,3))  
a  
b=np.transpose(a)  
b  

array([[0, 3],
       [1, 4],
       [2, 5]])

In [50]:
a= np.array([[1, 2], [4, 5], [7, 8]])  
a  
b=np.transpose(a, (1,0))  
b   

array([[1, 4, 7],
       [2, 5, 8]])